// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"anest.top/youli/cmd/http/controller"
	"anest.top/youli/cmd/http/server"
	"anest.top/youli/config"
	"anest.top/youli/internal/application/handler"
	"anest.top/youli/internal/data/store"
	"anest.top/youli/internal/domain/external"
	"context"
)

// Injectors from wire.go:

func InitApp(ctx context.Context) (*server.App, error) {
	configConfig := config.NewConfig()
	db, err := store.NewMysql(configConfig)
	if err != nil {
		return nil, err
	}
	register := external.NewRegister(db)
	handlerHandler := handler.NewHandler(register)
	authController := controller.NewAuthController(handlerHandler)
	routerController := controller.NewController(authController)
	app, err := server.NewServer(ctx, routerController, configConfig)
	if err != nil {
		return nil, err
	}
	return app, nil
}
